#!/usr/bin/env bash
# ~rts/oarion7

# Requires surf: git clone https://git.suckless.org/surf
#                apt get libwebkit2gtk-4.1-dev libgcr-3-dev
#                make clean install

path="$(dirname "$(realpath "$0")")"

url="https://tanzil.net"

surf() {
    /usr/local/bin/surf -N -C "$path/style.css" -r "$path/script.js" -z 2 "$@" 
}

[[ "$1" =~ ^[0-9]*:[0-9]*$ ]] && url="$url/#${1}" # Takes 1 optional argument: "sūrah:āyah" 

surf "$url"

